#!/usr/bin/env php
<?php
/**
 * 入口程序
 *
 * @author Yametei
 * @version $Id: shell 520 2012-04-08 08:03:18Z yametei $
 */

define('DESIRE_SAPI', 'wm');

$_directories = array(
	dirname(__FILE__) . '/configs/local/configuration.php',// local first
	dirname(__FILE__) . '/configs/configuration.php',
);

foreach ($_directories as $_file) {
	if (is_file($_file)) {
		require_once $_file;
		break;
	}
}
unset($_directories, $_file);

if (!class_exists('Desire_Version')) {//check framework has already loaded
	trigger_error("The desire framework not loaded correctly", E_USER_ERROR);
}

$ip = 0;
while(1) {
	//print_r(Desire_Http::post('http://10.0.0.90:8801', [[
	print_r(Desire_Http::post('http://127.0.0.1:1206/kit/ip', [[
	't' => time(),
	'ip' => long2ip($ip++),
	]]));

		//print_r(Desire_Http::get('http://127.0.0.1:1206/kit/ip?ip='.long2ip($ip++)));
	usleep(mt_rand(100, 1000));
}
