#!/usr/bin/env php
<?php
/**
 * 入口程序
 *
 * @author Yametei
 * @version $Id: shell 520 2012-04-08 08:03:18Z yametei $
 */

define('DESIRE_SAPI', 'wm');

$_directories = array(
	dirname(__FILE__) . '/configs/local/configuration.php',// local first
	dirname(__FILE__) . '/configs/configuration.php',
);

foreach ($_directories as $_file) {
	if (is_file($_file)) {
		require_once $_file;
		break;
	}
}
unset($_directories, $_file);

if (!class_exists('Desire_Version')) {//check framework has already loaded
	trigger_error("The desire framework not loaded correctly", E_USER_ERROR);
}


print_r(Desire_Http::post('http://127.0.0.1:1206/runtime?FDSA=23EDC&FDSA=3EWFD', [[
't' => time(),
'm' => Desire_Math::randomReadableString(123),
],[
	'af' => '/Users/zhangzhihua/Downloads/201461217043.png',
	'af2' => '/Users/zhangzhihua/Downloads/201461217043.png',
]]));